"""create hybrid retrieval and knowledge graph tables

Revision ID: b3b7d1e8c5fa
Revises: a9d8f7e6d5c4
Create Date: 2026-07-03 21:12:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b7d1e8c5fa'
down_revision = 'a9d8f7e6d5c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'knowledge_nodes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_id'), 'knowledge_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_workspace_id'), 'knowledge_nodes', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_name'), 'knowledge_nodes', ['name'], unique=False)

    op.create_table(
        'knowledge_edges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('source_node_id', sa.Integer(), nullable=False),
        sa.Column('target_node_id', sa.Integer(), nullable=False),
        sa.Column('relation_type', sa.String(length=50), nullable=False),
        sa.Column('weight', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_edges_id'), 'knowledge_edges', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_workspace_id'), 'knowledge_edges', ['workspace_id'], unique=False)

    op.create_table(
        'retrieval_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('query', sa.String(length=500), nullable=False),
        sa.Column('intent', sa.String(length=50), nullable=False),
        sa.Column('latency_ms', sa.Float(), nullable=False),
        sa.Column('confidence_score', sa.Float(), nullable=False),
        sa.Column('chunks_retrieved', sa.Integer(), nullable=False),
        sa.Column('chunks_accepted', sa.Integer(), nullable=False),
        sa.Column('chunks_rejected', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_logs_id'), 'retrieval_logs', ['id'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_workspace_id'), 'retrieval_logs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_logs_workspace_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_id'), table_name='retrieval_logs')
    op.drop_table('retrieval_logs')

    op.drop_index(op.f('ix_knowledge_edges_workspace_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_id'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')

    op.drop_index(op.f('ix_knowledge_nodes_name'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_workspace_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
