"""create final layer tables

Revision ID: bd7f8e91d0e2
Revises: e7c90b0e517e
Create Date: 2026-07-03 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7f8e91d0e2'
down_revision: Union[str, None] = 'e7c90b0e517e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'workspace_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('thumbnail', sa.String(length=255), nullable=True),
        sa.Column('configuration', sa.JSON(), nullable=False),
        sa.Column('is_public', sa.Boolean(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_templates_id'), 'workspace_templates', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_templates_category'), 'workspace_templates', ['category'], unique=False)
    op.create_index(op.f('ix_workspace_templates_is_public'), 'workspace_templates', ['is_public'], unique=False)
    op.create_index(op.f('ix_workspace_templates_owner_id'), 'workspace_templates', ['owner_id'], unique=False)

    op.create_table(
        'conversation_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('before_content', sa.Text(), nullable=False),
        sa.Column('after_content', sa.Text(), nullable=False),
        sa.Column('editor_id', sa.Integer(), nullable=False),
        sa.Column('reason', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_versions_id'), 'conversation_versions', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_versions_conversation_id'), 'conversation_versions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_versions_editor_id'), 'conversation_versions', ['editor_id'], unique=False)
    op.create_index(op.f('ix_conversation_versions_created_at'), 'conversation_versions', ['created_at'], unique=False)

    # Add columns to workspaces table
    op.add_column('workspaces', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('primary_color', sa.String(length=7), nullable=True))
    op.add_column('workspaces', sa.Column('accent_color', sa.String(length=7), nullable=True))
    op.add_column('workspaces', sa.Column('theme', sa.String(length=20), nullable=True))
    op.add_column('workspaces', sa.Column('welcome_message', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('banner_url', sa.String(length=255), nullable=True))

    op.add_column('workspaces', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='UTC'))
    op.add_column('workspaces', sa.Column('language', sa.String(length=20), nullable=False, server_default='en'))
    op.add_column('workspaces', sa.Column('date_format', sa.String(length=20), nullable=False, server_default='YYYY-MM-DD'))
    op.add_column('workspaces', sa.Column('ai_model_preference', sa.String(length=50), nullable=True))
    op.add_column('workspaces', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    op.add_column('workspaces', sa.Column('guest_policy', sa.String(length=20), nullable=False, server_default='allowed'))
    op.add_column('workspaces', sa.Column('sharing_policy', sa.String(length=20), nullable=False, server_default='allowed'))
    op.add_column('workspaces', sa.Column('retention_period_days', sa.Integer(), nullable=True))
    op.add_column('workspaces', sa.Column('auto_archive_days', sa.Integer(), nullable=True))
    op.add_column('workspaces', sa.Column('history_size_limit', sa.Integer(), nullable=True))

    op.add_column('workspaces', sa.Column('disable_sharing', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workspaces', sa.Column('disable_exports', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workspaces', sa.Column('disable_public_links', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workspaces', sa.Column('disable_invite', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workspaces', sa.Column('disable_downloads', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workspaces', sa.Column('disable_comments', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workspaces', sa.Column('disable_reactions', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('workspaces', sa.Column('allowed_domains', sa.String(length=255), nullable=True))

    op.add_column('workspaces', sa.Column('plan', sa.String(length=20), nullable=False, server_default='free'))
    op.add_column('workspaces', sa.Column('region', sa.String(length=20), nullable=False, server_default='us'))
    op.add_column('workspaces', sa.Column('data_residency', sa.String(length=20), nullable=False, server_default='us'))
    op.add_column('workspaces', sa.Column('organization', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('license_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'license_key')
    op.drop_column('workspaces', 'organization')
    op.drop_column('workspaces', 'data_residency')
    op.drop_column('workspaces', 'region')
    op.drop_column('workspaces', 'plan')

    op.drop_column('workspaces', 'allowed_domains')
    op.drop_column('workspaces', 'disable_reactions')
    op.drop_column('workspaces', 'disable_comments')
    op.drop_column('workspaces', 'disable_downloads')
    op.drop_column('workspaces', 'disable_invite')
    op.drop_column('workspaces', 'disable_public_links')
    op.drop_column('workspaces', 'disable_exports')
    op.drop_column('workspaces', 'disable_sharing')

    op.drop_column('workspaces', 'history_size_limit')
    op.drop_column('workspaces', 'auto_archive_days')
    op.drop_column('workspaces', 'retention_period_days')
    op.drop_column('workspaces', 'sharing_policy')
    op.drop_column('workspaces', 'guest_policy')
    op.drop_column('workspaces', 'notification_preferences')
    op.drop_column('workspaces', 'ai_model_preference')
    op.drop_column('workspaces', 'date_format')
    op.drop_column('workspaces', 'language')
    op.drop_column('workspaces', 'timezone')

    op.drop_column('workspaces', 'banner_url')
    op.drop_column('workspaces', 'welcome_message')
    op.drop_column('workspaces', 'theme')
    op.drop_column('workspaces', 'accent_color')
    op.drop_column('workspaces', 'primary_color')
    op.drop_column('workspaces', 'logo_url')

    op.drop_index(op.f('ix_conversation_versions_created_at'), table_name='conversation_versions')
    op.drop_index(op.f('ix_conversation_versions_editor_id'), table_name='conversation_versions')
    op.drop_index(op.f('ix_conversation_versions_conversation_id'), table_name='conversation_versions')
    op.drop_index(op.f('ix_conversation_versions_id'), table_name='conversation_versions')
    op.drop_table('conversation_versions')

    op.drop_index(op.f('ix_workspace_templates_owner_id'), table_name='workspace_templates')
    op.drop_index(op.f('ix_workspace_templates_is_public'), table_name='workspace_templates')
    op.drop_index(op.f('ix_workspace_templates_category'), table_name='workspace_templates')
    op.drop_index(op.f('ix_workspace_templates_id'), table_name='workspace_templates')
    op.drop_table('workspace_templates')
    # ### end Alembic commands ###
