"""create training project tables

Revision ID: e5d4c3b2a1f0
Revises: d4f3e2a1b0c9
Create Date: 2026-07-03 21:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d4c3b2a1f0'
down_revision = 'd4f3e2a1b0c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'training_projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('base_model', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_projects_id'), 'training_projects', ['id'], unique=False)
    op.create_index(op.f('ix_training_projects_workspace_id'), 'training_projects', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_training_projects_name'), 'training_projects', ['name'], unique=False)
    op.create_index(op.f('ix_training_projects_status'), 'training_projects', ['status'], unique=False)

    op.create_table(
        'training_runs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('dataset_project_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('lora_config', sa.JSON(), nullable=True),
        sa.Column('training_config', sa.JSON(), nullable=True),
        sa.Column('current_epoch', sa.Integer(), nullable=False),
        sa.Column('current_step', sa.Integer(), nullable=False),
        sa.Column('loss', sa.Float(), nullable=True),
        sa.Column('gpu_usage_pct', sa.Float(), nullable=True),
        sa.Column('vram_usage_gb', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['training_projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_runs_id'), 'training_runs', ['id'], unique=False)
    op.create_index(op.f('ix_training_runs_project_id'), 'training_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_training_runs_dataset_project_id'), 'training_runs', ['dataset_project_id'], unique=False)
    op.create_index(op.f('ix_training_runs_status'), 'training_runs', ['status'], unique=False)

    op.create_table(
        'training_artifacts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('run_id', sa.Integer(), nullable=False),
        sa.Column('artifact_type', sa.String(length=50), nullable=False),
        sa.Column('storage_path', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['run_id'], ['training_runs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_artifacts_id'), 'training_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_training_artifacts_run_id'), 'training_artifacts', ['run_id'], unique=False)

    op.create_table(
        'training_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('run_id', sa.Integer(), nullable=False),
        sa.Column('step', sa.Integer(), nullable=False),
        sa.Column('loss', sa.Float(), nullable=False),
        sa.Column('learning_rate', sa.Float(), nullable=False),
        sa.Column('tokens_per_sec', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['run_id'], ['training_runs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_logs_id'), 'training_logs', ['id'], unique=False)
    op.create_index(op.f('ix_training_logs_run_id'), 'training_logs', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_logs_run_id'), table_name='training_logs')
    op.drop_index(op.f('ix_training_logs_id'), table_name='training_logs')
    op.drop_table('training_logs')

    op.drop_index(op.f('ix_training_artifacts_run_id'), table_name='training_artifacts')
    op.drop_index(op.f('ix_training_artifacts_id'), table_name='training_artifacts')
    op.drop_table('training_artifacts')

    op.drop_index(op.f('ix_training_runs_status'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_dataset_project_id'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_project_id'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_id'), table_name='training_runs')
    op.drop_table('training_runs')

    op.drop_index(op.f('ix_training_projects_status'), table_name='training_projects')
    op.drop_index(op.f('ix_training_projects_name'), table_name='training_projects')
    op.drop_index(op.f('ix_training_projects_workspace_id'), table_name='training_projects')
    op.drop_index(op.f('ix_training_projects_id'), table_name='training_projects')
    op.drop_table('training_projects')
    # ### end Alembic commands ###
