"""create folders table

Revision ID: fc7a61d8a0c2
Revises: 70f7e4f9b8c0
Create Date: 2026-07-03 19:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7a61d8a0c2'
down_revision: Union[str, None] = '70f7e4f9b8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'folders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=60), nullable=False),
        sa.Column('color', sa.String(length=20), nullable=False),
        sa.Column('icon', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_id'), 'folders', ['id'], unique=False)
    op.create_index(op.f('ix_folders_workspace_id'), 'folders', ['workspace_id'], unique=False)

    op.add_column('conversations', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('conversations', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('conversations', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='false'))

    op.create_foreign_key(
        'fk_conversations_folder_id_folders',
        'conversations',
        'folders',
        ['folder_id'],
        ['id'],
        ondelete='SET NULL'
    )
    
    op.create_index(op.f('ix_conversations_folder_id'), 'conversations', ['folder_id'], unique=False)
    op.create_index(op.f('ix_conversations_position'), 'conversations', ['position'], unique=False)
    op.create_index(op.f('ix_conversations_is_pinned'), 'conversations', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_conversations_is_archived'), 'conversations', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_is_archived'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_pinned'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_position'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_folder_id'), table_name='conversations')
    op.drop_constraint('fk_conversations_folder_id_folders', 'conversations', type_='foreignkey')
    
    op.drop_column('conversations', 'is_archived')
    op.drop_column('conversations', 'is_pinned')
    op.drop_column('conversations', 'position')
    op.drop_column('conversations', 'folder_id')

    op.drop_index(op.f('ix_folders_workspace_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_id'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
