-- ==============================================================================
-- Nexora AI — Supabase Full Schema (36 tables) — Generated 2026-08-29
-- Source: apps/backend/app/models/*.py (26 files) + alembic/versions/*.py (16)
-- Run: Supabase Dashboard -> SQL Editor -> New Query -> Paste -> Run
-- Alt: DATABASE_URL=postgresql://... alembic upgrade head (same result)
-- Note: Public repo vishvam26/nexora-qwen3.5-4b-merged, Qdrant already set in Render
-- ==============================================================================

BEGIN;

-- 1. Companies (enterprise, must be first for FK)
CREATE TABLE IF NOT EXISTS companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  plan VARCHAR(20) DEFAULT 'FREE',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS company_settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER UNIQUE REFERENCES companies(id) ON DELETE CASCADE,
  default_llm VARCHAR(50) DEFAULT 'gemini-1.5-flash',
  theme VARCHAR(20) DEFAULT 'dark',
  logo VARCHAR(255),
  max_file_size INTEGER DEFAULT 10485760,
  allowed_extensions JSONB
);
CREATE TABLE IF NOT EXISTS company_secrets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER REFERENCES companies(id) ON DELETE CASCADE,
  provider VARCHAR(50),
  encrypted_api_key VARCHAR(512)
);

-- 2. Users (self-ref manager_id, later company_id)
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  is_active BOOLEAN DEFAULT true,
  manager_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  company_role VARCHAR(20) DEFAULT 'EMPLOYEE',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users(email);
CREATE INDEX IF NOT EXISTS ix_users_manager_id ON users(manager_id);

-- Seed default company
INSERT INTO companies (id, name, plan) VALUES (1, 'Default Company', 'FREE') ON CONFLICT (id) DO NOTHING;

-- 3. Workspaces + related
CREATE TABLE IF NOT EXISTS workspaces (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(60) NOT NULL,
  description TEXT,
  icon VARCHAR(50) DEFAULT '💼',
  color VARCHAR(7) DEFAULT '#4F46E5',
  visibility VARCHAR(20) DEFAULT 'private',
  status VARCHAR(20) DEFAULT 'active',
  logo_url VARCHAR(255),
  primary_color VARCHAR(7),
  accent_color VARCHAR(7),
  theme VARCHAR(20),
  welcome_message TEXT,
  banner_url VARCHAR(255),
  timezone VARCHAR(50) DEFAULT 'UTC',
  language VARCHAR(20) DEFAULT 'en',
  date_format VARCHAR(20) DEFAULT 'YYYY-MM-DD',
  ai_model_preference VARCHAR(50),
  notification_preferences JSONB,
  guest_policy VARCHAR(20) DEFAULT 'allowed',
  sharing_policy VARCHAR(20) DEFAULT 'allowed',
  retention_period_days INTEGER,
  auto_archive_days INTEGER,
  history_size_limit INTEGER,
  disable_sharing BOOLEAN DEFAULT false,
  disable_exports BOOLEAN DEFAULT false,
  disable_public_links BOOLEAN DEFAULT false,
  disable_invite BOOLEAN DEFAULT false,
  disable_downloads BOOLEAN DEFAULT false,
  disable_comments BOOLEAN DEFAULT false,
  disable_reactions BOOLEAN DEFAULT false,
  allowed_domains VARCHAR(255),
  plan VARCHAR(20) DEFAULT 'free',
  region VARCHAR(20) DEFAULT 'us',
  data_residency VARCHAR(20) DEFAULT 'us',
  organization VARCHAR(100),
  license_key VARCHAR(100),
  company_id INTEGER REFERENCES companies(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_workspaces_owner_id ON workspaces(owner_id);
CREATE INDEX IF NOT EXISTS ix_workspaces_visibility ON workspaces(visibility);
CREATE INDEX IF NOT EXISTS ix_workspaces_status ON workspaces(status);
CREATE INDEX IF NOT EXISTS ix_workspaces_created_at ON workspaces(created_at);

CREATE TABLE IF NOT EXISTS folders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name VARCHAR(60) NOT NULL,
  color VARCHAR(20) DEFAULT 'Blue',
  icon VARCHAR(50) DEFAULT '📁',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_folders_workspace_id ON folders(workspace_id);

CREATE TABLE IF NOT EXISTS workspace_members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workspace_role VARCHAR(20) DEFAULT 'EMPLOYEE',
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  last_active TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT true,
  UNIQUE(workspace_id, user_id)
);
CREATE INDEX IF NOT EXISTS ix_workspace_members_workspace_id ON workspace_members(workspace_id);
CREATE INDEX IF NOT EXISTS ix_workspace_members_user_id ON workspace_members(user_id);

CREATE TABLE IF NOT EXISTS workspace_invitations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  invited_by INTEGER REFERENCES users(id) ON DELETE CASCADE,
  role VARCHAR(20) DEFAULT 'VIEWER',
  token VARCHAR(36) UNIQUE NOT NULL,
  status VARCHAR(20) DEFAULT 'PENDING',
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  accepted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_workspace_invitations_workspace_id ON workspace_invitations(workspace_id);
CREATE INDEX IF NOT EXISTS ix_workspace_invitations_email ON workspace_invitations(email);

CREATE TABLE IF NOT EXISTS invitations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'EMPLOYEE',
  token VARCHAR(36) UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ,
  accepted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS workspace_templates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  category VARCHAR(50),
  thumbnail VARCHAR(255),
  configuration JSONB NOT NULL,
  is_public BOOLEAN DEFAULT true,
  owner_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Conversations / Messages
CREATE TABLE IF NOT EXISTS conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workspace_id INTEGER REFERENCES workspaces(id) ON DELETE CASCADE,
  folder_id INTEGER REFERENCES folders(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT,
  position INTEGER DEFAULT 0,
  is_pinned BOOLEAN DEFAULT false,
  is_archived BOOLEAN DEFAULT false,
  is_deleted BOOLEAN DEFAULT false,
  share_token VARCHAR(36) UNIQUE,
  share_expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_conversations_folder_id ON conversations(folder_id);
CREATE INDEX IF NOT EXISTS ix_conversations_share_token ON conversations(share_token);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  sources JSONB,
  is_deleted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_messages_conversation_id ON messages(conversation_id);

CREATE TABLE IF NOT EXISTS conversation_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  parent_comment_id INTEGER REFERENCES conversation_comments(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  edited_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS mentions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id INTEGER NOT NULL REFERENCES conversation_comments(id) ON DELETE CASCADE,
  mentioned_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS message_reactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  emoji VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(message_id, user_id, emoji)
);
CREATE TABLE IF NOT EXISTS favorites (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, conversation_id)
);
CREATE TABLE IF NOT EXISTS conversation_versions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  before_content TEXT NOT NULL,
  after_content TEXT NOT NULL,
  editor_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reason VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  type VARCHAR(30) NOT NULL,
  title VARCHAR(100) NOT NULL,
  message VARCHAR(255) NOT NULL,
  entity_type VARCHAR(50),
  entity_id INTEGER,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS activity_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action VARCHAR(100) NOT NULL,
  entity VARCHAR(50) NOT NULL,
  entity_id INTEGER,
  metadata JSONB,
  ip_address VARCHAR(45),
  device VARCHAR(255),
  browser VARCHAR(255),
  status VARCHAR(20) DEFAULT 'SUCCESS',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Knowledge RAG
CREATE TABLE IF NOT EXISTS knowledge_bases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid VARCHAR(36) NOT NULL UNIQUE,
  workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  icon VARCHAR(50) DEFAULT '📚',
  color VARCHAR(7) DEFAULT '#10B981',
  visibility VARCHAR(20) DEFAULT 'private',
  created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS knowledge_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  knowledge_base_id INTEGER NOT NULL REFERENCES knowledge_bases(id) ON DELETE CASCADE,
  filename VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  size INTEGER NOT NULL,
  status VARCHAR(30) DEFAULT 'Uploading',
  pages INTEGER,
  language VARCHAR(10),
  checksum VARCHAR(64),
  storage_path VARCHAR(255) NOT NULL,
  visibility VARCHAR(20) DEFAULT 'WORKSPACE',
  doc_metadata JSONB,
  uploaded_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS document_chunks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id INTEGER NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
  chunk_index INTEGER NOT NULL,
  text TEXT NOT NULL,
  token_count INTEGER NOT NULL,
  page INTEGER,
  section VARCHAR(100),
  chunk_metadata JSONB,
  embedding_status VARCHAR(30) DEFAULT 'Pending',
  embedding JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_document_chunks_document_id ON document_chunks(document_id);
CREATE TABLE IF NOT EXISTS document_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id INTEGER NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS knowledge_nodes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER NOT NULL,
  name VARCHAR(100) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  document_id INTEGER REFERENCES knowledge_documents(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_knowledge_nodes_workspace_id ON knowledge_nodes(workspace_id);
CREATE TABLE IF NOT EXISTS knowledge_edges (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER NOT NULL,
  source_node_id INTEGER NOT NULL REFERENCES knowledge_nodes(id) ON DELETE CASCADE,
  target_node_id INTEGER NOT NULL REFERENCES knowledge_nodes(id) ON DELETE CASCADE,
  relation_type VARCHAR(50) NOT NULL,
  weight DOUBLE PRECISION DEFAULT 1.0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS retrieval_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER NOT NULL,
  query VARCHAR(500) NOT NULL,
  intent VARCHAR(50),
  latency_ms DOUBLE PRECISION,
  confidence_score DOUBLE PRECISION,
  chunks_retrieved INTEGER,
  chunks_accepted INTEGER,
  chunks_rejected INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS calendar_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR NOT NULL,
  description TEXT,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  attendees TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  title VARCHAR(500) NOT NULL,
  description TEXT,
  assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(50) DEFAULT 'pending',
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Feedback / Dataset / Training
CREATE TABLE IF NOT EXISTS chat_feedback (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  rating INTEGER,
  thumbs_up BOOLEAN DEFAULT false,
  thumbs_down BOOLEAN DEFAULT false,
  feedback VARCHAR(500),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  faithfulness DOUBLE PRECISION,
  answer_relevance DOUBLE PRECISION,
  context_recall DOUBLE PRECISION,
  hallucination_score DOUBLE PRECISION,
  confidence_score DOUBLE PRECISION,
  priority VARCHAR(50) DEFAULT 'LOW',
  query_hash VARCHAR(100),
  review_status VARCHAR(50) DEFAULT 'pending',
  reviewed_at TIMESTAMPTZ,
  is_flagged_for_tuning BOOLEAN DEFAULT false,
  model_version VARCHAR(100) DEFAULT 'nexora-v1',
  dataset_version VARCHAR(100) DEFAULT 'ds-v1',
  rag_pipeline_version VARCHAR(100) DEFAULT 'rag-v2.1',
  root_cause VARCHAR(100),
  domain_tag VARCHAR(100),
  response_time_ms INTEGER,
  replay_query TEXT,
  replay_prompt TEXT,
  replay_chunks TEXT
);
CREATE TABLE IF NOT EXISTS dataset_projects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  language VARCHAR(50) DEFAULT 'English',
  visibility VARCHAR(20) DEFAULT 'private',
  created_by INTEGER REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(30) DEFAULT 'Draft',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS dataset_versions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES dataset_projects(id) ON DELETE CASCADE,
  version_tag VARCHAR(20) NOT NULL,
  sample_count INTEGER DEFAULT 0,
  token_count INTEGER DEFAULT 0,
  storage_path VARCHAR(255) NOT NULL,
  version_metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS dataset_review_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES dataset_projects(id) ON DELETE CASCADE,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  reviewer_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  review_status VARCHAR(20) DEFAULT 'Pending',
  quality_score DOUBLE PRECISION DEFAULT 0.0,
  comments VARCHAR(500)
);
CREATE TABLE IF NOT EXISTS training_projects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id INTEGER,
  name VARCHAR(100) NOT NULL,
  base_model VARCHAR(100) NOT NULL,
  status VARCHAR(30) DEFAULT 'Draft',
  created_by INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS training_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES training_projects(id) ON DELETE CASCADE,
  dataset_project_id INTEGER,
  status VARCHAR(30) DEFAULT 'Queued',
  lora_config JSONB,
  training_config JSONB,
  current_epoch INTEGER DEFAULT 0,
  current_step INTEGER DEFAULT 0,
  loss DOUBLE PRECISION,
  gpu_usage_pct DOUBLE PRECISION,
  vram_usage_gb DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS training_artifacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id INTEGER NOT NULL REFERENCES training_runs(id) ON DELETE CASCADE,
  artifact_type VARCHAR(50) NOT NULL,
  storage_path VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS training_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id INTEGER NOT NULL REFERENCES training_runs(id) ON DELETE CASCADE,
  step INTEGER NOT NULL,
  loss DOUBLE PRECISION NOT NULL,
  learning_rate DOUBLE PRECISION NOT NULL,
  tokens_per_sec DOUBLE PRECISION DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Optional: backfill user company_id if needed
UPDATE users SET company_id=1 WHERE company_id IS NULL;

COMMIT;

-- Post-run: Supabase -> Table Editor -> verify 36 tables
-- Next: set DATABASE_URL in apps/backend/.env and Render, then alembic not needed
