"use client";

import { useState, useEffect, useCallback } from "react";
import { useChatStore } from "../stores/chat-store";
import {
  Mail, Send, Loader2, AlertCircle, CheckCircle2,
  Paperclip, Sparkles, FileText, ArrowRight, RefreshCw,
  Info
} from "lucide-react";

import { apiService, API_BASE_URL } from "../services/api-service";

const API_BASE = API_BASE_URL;

interface GeneratedReport {
  report_id: string;
  report_type: string;
  export_format: string;
  generated_at: string;
}

export default function EmailStudio() {
  const { token, documents } = useChatStore();

  // SMTP form states
  const [toEmail, setToEmail] = useState("cfo@company.com");
  const [subject, setSubject] = useState("Q2 Revenue Analytics & Churn Report");
  const [body, setBody] = useState(
    "<h3>Executive Analytics Summary</h3><p>Please find attached the exported Q2 performance metrics report generated by Nexora AI.</p>"
  );
  const [selectedReportId, setSelectedReportId] = useState<string>("");

  // Reports directory list
  const [reports, setReports] = useState<GeneratedReport[]>([]);
  const [loadingReports, setLoadingReports] = useState(false);
  const [sending, setSending] = useState(false);
  const [successMsg, setSuccessMsg] = useState("");
  const [errorMsg, setErrorMsg] = useState("");

  // AI Copilot state
  const [naturalLanguage, setNaturalLanguage] = useState("");
  const [drafting, setDrafting] = useState(false);

  const headers = useCallback(() => ({
    "Content-Type": "application/json",
    "ngrok-skip-browser-warning": "69420",
    Authorization: `Bearer ${token}`
  }), [token]);

  const loadReports = useCallback(async () => {
    setLoadingReports(true);
    // Find reports for the first document in the user's workspace
    const firstDoc = documents[0];
    if (firstDoc) {
      try {
        const res = await fetch(`${API_BASE}/reports/list/${firstDoc.id}`, { headers: headers() });
        if (res.ok) setReports(await res.json());
      } catch { /* ignore */ }
    }
    setLoadingReports(false);
  }, [documents, headers]);

  useEffect(() => {
    loadReports();
  }, [loadReports]);

  const handleSendEmail = async () => {
    if (!toEmail.trim() || !subject.trim() || !body.trim()) {
      setErrorMsg("All email fields (To, Subject, Message) are required.");
      return;
    }

    setSending(true);
    setErrorMsg("");
    setSuccessMsg("");

    try {
      const res = await fetch(`${API_BASE}/email/send`, {
        method: "POST",
        headers: headers(),
        body: JSON.stringify({
          to_email: toEmail,
          subject,
          body,
          report_id: selectedReportId || null
        })
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.detail || "SMTP dispatch failed.");
      }
      
      if (data.mock_mode) {
        setSuccessMsg("Development Loop: Mock email compiled and logged successfully.");
      } else {
        setSuccessMsg(`Email successfully sent to ${toEmail} via SMTP.`);
      }
    } catch (e: any) {
      setErrorMsg(e.message || "Dispatch error occurred.");
    } finally {
      setSending(false);
    }
  };

  const getOrCreateConversationId = async () => {
    const state = useChatStore.getState();
    const existing = state.conversations;
    if (existing && existing.length > 0) {
      return existing[0].id;
    }
    const wsId = state.activeWorkspace?.id || state.workspaces[0]?.id;
    if (!wsId) {
      throw new Error("No active workspace found to start chat.");
    }
    const convo = await apiService.createConversation("System Copilot Chat", wsId);
    return convo.id;
  };

  const handleAIDrafter = async () => {
    if (!naturalLanguage.trim()) return;
    setDrafting(true);
    try {
      const prompt = `Draft a professional business email based on: "${naturalLanguage}". Reply ONLY with a valid JSON object matching keys: {"subject": "string", "body": "HTML string description"}. Do not return any markdown wrappers, just raw JSON.`;
      
      const convoId = await getOrCreateConversationId();
      const res = await fetch(`${API_BASE}/chat`, {
        method: "POST",
        headers: headers(),
        body: JSON.stringify({
          conversation_id: convoId,
          message: prompt,
          grounded: false
        })
      });
      const data = await res.json();
      if (res.ok && data.assistant_message?.content) {
        const cleanJSON = data.assistant_message.content.replace(/```json|```/g, "").trim();
        const parsed = JSON.parse(cleanJSON);
        if (parsed.subject) setSubject(parsed.subject);
        if (parsed.body) setBody(parsed.body);
      }
    } catch (err) {
      console.error("AI Drafter failed:", err);
    }
    setDrafting(false);
  };

  return (
    <div className="flex h-screen w-full overflow-hidden bg-[#09090b] text-[#f4f4f5]">
      {/* ── Left Workspace: Form Inputs ─────────────────────────────── */}
      <div className="flex flex-1 flex-col border-r border-zinc-800 overflow-y-auto">
        <div className="border-b border-zinc-800 px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-500/20 border border-indigo-500/30">
              <Mail className="h-4 w-4 text-indigo-400" />
            </div>
            <div>
              <h2 className="text-xs font-bold text-white uppercase tracking-wider">Email Studio</h2>
              <p className="text-[10px] text-zinc-500">Draft & send SMTP notifications</p>
            </div>
          </div>

          <button
            onClick={handleSendEmail}
            disabled={sending}
            className="flex items-center gap-1.5 rounded-lg bg-indigo-600 px-4 py-1.5 text-xs font-bold text-white hover:bg-indigo-500 disabled:opacity-50 transition"
          >
            {sending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Send className="h-3.5 w-3.5" />}
            Send Email
          </button>
        </div>

        <div className="flex flex-col gap-5 p-6">
          {/* Status Banners */}
          {successMsg && (
            <div className="flex items-start gap-2.5 rounded-xl border border-emerald-500/20 bg-emerald-500/5 px-4 py-3">
              <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400" />
              <p className="text-xs text-emerald-300">{successMsg}</p>
            </div>
          )}
          {errorMsg && (
            <div className="flex items-start gap-2.5 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3">
              <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-red-400" />
              <p className="text-xs text-red-300">{errorMsg}</p>
            </div>
          )}

          {/* AI Copilot Drafter */}
          <div className="flex items-center gap-2.5 rounded-xl border border-indigo-500/20 bg-indigo-500/5 px-4 py-2.5">
            <Sparkles className="h-4 w-4 text-indigo-400 shrink-0" />
            <input
              type="text"
              value={naturalLanguage}
              onChange={(e) => setNaturalLanguage(e.target.value)}
              onKeyDown={(e) => { if (e.key === "Enter") handleAIDrafter(); }}
              placeholder="Ask AI Copilot to draft (e.g. 'Write a report share email to CFO')"
              className="flex-1 bg-transparent text-xs text-zinc-200 placeholder:text-zinc-500 focus:outline-none"
            />
            <button
              onClick={handleAIDrafter}
              disabled={drafting || !naturalLanguage.trim()}
              className="rounded p-1 text-indigo-400 hover:bg-indigo-500/10 disabled:opacity-30"
            >
              {drafting ? <Loader2 className="h-4 w-4 animate-spin" /> : <ArrowRight className="h-4 w-4" />}
            </button>
          </div>

          {/* Form Fields */}
          <div className="flex flex-col gap-4">
            <div>
              <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-wider text-zinc-500">To (Recipient)</label>
              <input
                type="email"
                value={toEmail}
                onChange={(e) => setToEmail(e.target.value)}
                className="w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-xs text-zinc-200 focus:border-indigo-500 focus:outline-none"
              />
            </div>

            <div>
              <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-wider text-zinc-500">Subject Line</label>
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                className="w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-xs text-zinc-200 focus:border-indigo-500 focus:outline-none"
              />
            </div>

            {/* Reports Attachment */}
            <div>
              <label className="mb-1.5 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider text-zinc-500">
                <Paperclip className="h-3.5 w-3.5" /> Attach Analytics Report
              </label>
              <div className="relative">
                <select
                  value={selectedReportId}
                  onChange={(e) => setSelectedReportId(e.target.value)}
                  className="w-full appearance-none rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 text-xs text-zinc-200 focus:border-indigo-500 focus:outline-none pr-8"
                >
                  <option value="">— No Attachment —</option>
                  {reports.map((rep) => (
                    <option key={rep.report_id} value={rep.report_id}>
                      {rep.report_type.replace("_", " ")} ({rep.export_format.toUpperCase()}) — {rep.report_id.slice(0, 10)}
                    </option>
                  ))}
                </select>
                <ChevronDown className="pointer-events-none absolute right-2.5 top-2.5 h-3.5 w-3.5 text-zinc-500" />
              </div>
            </div>

            <div>
              <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-wider text-zinc-500">Message Body (HTML enabled)</label>
              <textarea
                value={body}
                onChange={(e) => setBody(e.target.value)}
                rows={6}
                className="w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2 font-mono text-xs text-zinc-200 focus:border-indigo-500 focus:outline-none resize-y"
              />
            </div>
          </div>
        </div>
      </div>

      {/* ── Right Panel: Envelope Visual Preview ───────────────────── */}
      <div className="flex w-96 shrink-0 flex-col bg-zinc-950/20 overflow-hidden">
        <div className="border-b border-zinc-800 px-5 py-4">
          <h2 className="text-xs font-bold text-white uppercase tracking-wider">Envelope Preview</h2>
          <p className="text-[10px] text-zinc-500">Visual message template</p>
        </div>

        <div className="flex-1 overflow-y-auto p-5">
          <div className="rounded-xl border border-zinc-800 bg-[#0d0d0e] p-5 shadow-2xl relative">
            {/* Header Stamp */}
            <div className="absolute top-4 right-4 text-[9px] font-bold text-zinc-700 border border-zinc-700 px-1.5 py-0.5 rounded uppercase tracking-wider font-mono">
              SMTP
            </div>

            {/* To/From Headers */}
            <div className="flex flex-col gap-2 border-b border-zinc-800 pb-4 mb-4 text-xs">
              <div>
                <span className="text-zinc-600 font-semibold uppercase tracking-wider text-[9px] block">From</span>
                <span className="text-zinc-400 font-mono">noreply@nexora.ai</span>
              </div>
              <div>
                <span className="text-zinc-600 font-semibold uppercase tracking-wider text-[9px] block">To</span>
                <span className="text-zinc-200 font-mono">{toEmail || "cfo@company.com"}</span>
              </div>
              <div>
                <span className="text-zinc-600 font-semibold uppercase tracking-wider text-[9px] block">Subject</span>
                <span className="text-zinc-100 font-medium">{subject || "Q2 Revenue Analytics & Churn Report"}</span>
              </div>
              {selectedReportId && (
                <div className="flex items-center gap-1.5 text-indigo-400 text-[10px] mt-1 font-semibold">
                  <Paperclip className="h-3.5 w-3.5" />
                  <span>nexora_report_{selectedReportId.slice(0, 8)}.pdf (Attached)</span>
                </div>
              )}
            </div>

            {/* Rendered HTML message block */}
            <div className="text-xs text-zinc-300 leading-relaxed min-h-[150px] bg-[#111112] p-4 rounded-lg border border-zinc-900/60 overflow-y-auto max-h-96">
              <div dangerouslySetInnerHTML={{ __html: body }} />
            </div>

            {/* SMTP config alert footer */}
            <div className="mt-4 flex gap-2 rounded-lg border border-zinc-800 bg-zinc-900/40 p-3 text-[10px] text-zinc-500 leading-tight">
              <Info className="h-3.5 w-3.5 shrink-0 text-zinc-600" />
              <span>Ensure SMTP variables are configured in .env.production to dispatch actual emails via TLS. Mock mode will log envelopes locally in dev.</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
