import json
import requests
from typing import List, Generator
from fastapi import HTTPException, status
from app.config import settings
from app.providers.provider_interface import AIProviderInterface


class GeminiProvider(AIProviderInterface):
    """
    Provider implementation for Google Gemini API (using native REST API to support new AQ. key formats).
    """

    def __init__(self):
        self.api_key = settings.GOOGLE_API_KEY
        self.model = settings.GEMINI_MODEL

        if not self.api_key:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Google API Key (for Gemini) is not configured."
            )

    def _build_payload(self, messages: List[dict]) -> dict:
        contents = []
        system_instruction = None

        for msg in messages:
            role = msg.get("role")
            content = msg.get("content", "")
            
            if role == "system":
                system_instruction = {
                    "parts": [{"text": content}]
                }
            else:
                gemini_role = "model" if role == "assistant" else "user"
                contents.append({
                    "role": gemini_role,
                    "parts": [{"text": content}]
                })

        payload = {
            "contents": contents
        }
        if system_instruction:
            payload["systemInstruction"] = system_instruction
            
        return payload

    def generate_response(self, messages: List[dict]) -> str:
        try:
            payload = self._build_payload(messages)
            url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"
            
            res = requests.post(url, headers={"Content-Type": "application/json"}, json=payload, timeout=30)
            if res.status_code != 200:
                raise Exception(f"HTTP {res.status_code}: {res.text}")
                
            data = res.json()
            candidates = data.get("candidates", [])
            if not candidates:
                raise Exception("No response generated by Gemini API.")
                
            text = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
            return text
        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"Gemini API error: {str(e)}"
            )

    def generate_stream_response(self, messages: List[dict]) -> Generator[str, None, None]:
        try:
            payload = self._build_payload(messages)
            url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:streamGenerateContent?key={self.api_key}"
            
            res = requests.post(url, headers={"Content-Type": "application/json"}, json=payload, stream=True)
            if res.status_code != 200:
                raise Exception(f"HTTP {res.status_code}: {res.text}")
                
            for line in res.iter_lines():
                if line:
                    decoded = line.decode("utf-8").strip()
                    if decoded.startswith("["):
                        decoded = decoded[1:]
                    if decoded.endswith("]"):
                        decoded = decoded[:-1]
                    if decoded.startswith(","):
                        decoded = decoded[1:]
                        
                    decoded = decoded.strip()
                    if not decoded:
                        continue
                        
                    try:
                        data = json.loads(decoded)
                        text = data.get("candidates", [{}])[0].get("content", {}).get("parts", [{}])[0].get("text", "")
                        if text:
                            yield text
                    except Exception:
                        pass
        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"Gemini stream error: {str(e)}"
            )
